### ISSUE TITLE
Nuget Package?

### ISSUE THREAD

**Issue by jahead** [AuDigitalHealth/clinical-document-library-dotnet#1]
Hey guys,

Just saw this package. Which I wouldn't mind using. Is there any plans to publish onto Nuget? 
It would streamline how we would consume this packages and packages like these?

**Comment by adha-admin** [comment]
At this stage, we don't have any plans to convert to a nuget packages. Our licence only supports source code - not compiled.

**Comment by jahead** [comment]
Can I publish it as NuGet package? As it is the common modern way for the dotNet community to consume upstream packages into their build system?

If not what is your recommended way to consume this package?

**Comment by adha-admin** [comment]
You should be able to compile and just use the DLLs for now until we NUGET them.
Alternatively, you could NUGET them to a local server of your own and then import them that way into your project.

**Comment by jahead** [comment]
Yea that's our probable outcome until you guys turn it into a NuGet package. 
Our CI/CD sits outside out UNSW domain, so we are still looking for a better solution. We will likely clone the repo and publish the package to a NuGet repository Service that our CI/CD can access. 

If you intend to turn it into a NuGet package, do you mind keeping the issue open for us to track for when this becomes finished? Or opening another issue. That way we will know when to move back to your official package?
