### ISSUE TITLE
Sample projects fail when custom user OutputFolder provided as Args

### ISSUE THREAD

**Issue by angusmillar** [AuDigitalHealth/clinical-document-library-dotnet#2]
### Expected behaviour

* When a custom OutputFolder path is provided as an argument to either sample project (CDA.R5Samples or CDA.Sample), the applications should run without exception as long as the path provided is valid.

### Actual behaviour

* When a custom OutputFolder is provided as an argument to either sample project (CDA.R5Samples or CDA.Sample), the applications both throw an exception complaining that the Logo.png file cannot be found.

### Steps to reproduce

Either project (CDA.R5Samples or CDA.Sample), right click and choose 'properties', under 'Debug' add a valid system file path to the 'Command line Arguments' field. For example 'C:\temp\myoutput'

### Environment

Within Visual Studio 2017, clone from the repository and follow steps above to reproduce.

**Comment by adha-admin** [comment]
Thanks Angus.
We have reviewed your pull request and applied the necessary changes to the library and a few others.
They have been pushed up in a feature branch v4.5.1 and this will continue to be updated until it is ready to be tagged a v4.5.1 release.
